#!/usr/bin/env python3
"""Merge on-disk screenshots into docs/gallery.md.

Preserves existing entries, adds new ones, removes entries whose images
no longer exist.  Called by tool/take_app_screenshots.sh.
"""
import os, re, sys

CAPTIONS = {
    "monitor.png": (
        "### Monitor\n"
        "![Monitor tab](images/monitor.png)\n\n"
        "Live camera preview with detector status and the monitoring start control.\n"
    ),
    "events.png": (
        "### Events\n"
        "![Events tab](images/events.png)\n\n"
        "Recorded events with snapshot thumbnails, list/grid toggle and manual reload.\n"
    ),
    "settings.png": (
        "### Settings\n"
        "![Settings tab](images/settings.png)\n\n"
        "Camera selection and the collapsible configuration sections captured below.\n"
    ),
}

SECTION_CAPTIONS = {
    "detectors":       "Detector groups (camera/audio/combined/system) with per-detector mode and thresholds.",
    "regions":         "Inclusion/exclusion detection regions and the editor entry point.",
    "face_recognition":"Known-face enrolment and recognition toggle.",
    "channels":        "Notification channels (Pushover, webhook, e-mail, log) with test-send controls.",
    "schedule":        "Monitoring schedule windows with pre-/post-roll.",
    "video_clips":     "Local clip recording, date/time stamping and privacy masking.",
    "live_view":       "RTSP live stream, authentication and audio options.",
    "cloud_backup":    "Self-hosted backup of clips and snapshots.",
    "events":          "Event retention and clearing.",
    "advanced":        "Advanced diagnostics and maintenance actions.",
}

HEADER = (
    "# App gallery\n\n"
    "Screenshots generated by `tool/take_app_screenshots.sh` — re-run that script\n"
    "(after any layout change) rather than editing these files by hand.\n"
)

SCREEN_ORDER = ["monitor.png", "events.png", "settings.png"]
SECTION_ORDER = [
    "detectors", "regions", "face_recognition", "channels", "schedule",
    "video_clips", "live_view", "cloud_backup", "events", "advanced",
]

IMG_RE = re.compile(r"!\[.*?\]\((images/\S+\.png)\)")
SECTION_RE = re.compile(r"^### (.+)$", re.MULTILINE)


def parse_gallery(text):
    """Return {image_path: section_text} for every ### section with an image."""
    entries = {}
    parts = re.split(r"(?=^### )", text, flags=re.MULTILINE)
    for part in parts:
        m = IMG_RE.search(part)
        if m:
            entries[m.group(1)] = part.rstrip() + "\n"
    return entries


def build_gallery(img_dir, gallery_path):
    existing = {}
    if os.path.exists(gallery_path):
        with open(gallery_path) as f:
            existing = parse_gallery(f.read())

    # Prune entries whose images no longer exist.
    pruned = {
        path: text
        for path, text in existing.items()
        if os.path.exists(os.path.join(img_dir, os.path.basename(path)))
    }

    # Collect all image basenames that exist on disk.
    on_disk = set()
    for name in os.listdir(img_dir):
        if name.endswith(".png"):
            on_disk.add(name)

    # Determine which images need new entries.
    existing_basenames = {os.path.basename(p) for p in pruned}

    # Build ordered list of (image_path, section_text) for new entries.
    new_entries = []
    for name in SCREEN_ORDER:
        if name in on_disk and name not in existing_basenames:
            new_entries.append(("images/" + name, CAPTIONS[name] + "\n"))
    for slug in SECTION_ORDER:
        name = f"settings_{slug}.png"
        if name in on_disk and name not in existing_basenames:
            cap = SECTION_CAPTIONS.get(slug, "")
            new_entries.append((
                "images/" + name,
                f"### {slug.replace('_', ' ').title()}\n"
                f"![{slug.replace('_', ' ').title()} section](images/{name})\n\n"
                f"{cap}\n",
            ))

    # Merge: start from pruned existing in original file order, then append new.
    if os.path.exists(gallery_path):
        with open(gallery_path) as f:
            original = f.read()
        # Walk original text preserving order of existing entries.
        ordered = []
        parts = re.split(r"(?=^### )", original, flags=re.MULTILINE)
        for part in parts:
            m = IMG_RE.search(part)
            if m and m.group(1) in pruned:
                ordered.append(pruned[m.group(1)])
        # Add new screen entries after last screen section.
        screen_paths = {"images/" + n for n in SCREEN_ORDER}
        last_screen_idx = -1
        for i, text in enumerate(ordered):
            m2 = IMG_RE.search(text)
            if m2 and m2.group(1) in screen_paths:
                last_screen_idx = i
        insert_idx = last_screen_idx + 1
        for path, text in new_entries:
            if path in screen_paths:
                ordered.insert(insert_idx, text)
                insert_idx += 1
        # Append remaining (settings) new entries at end.
        for path, text in new_entries:
            if path not in screen_paths:
                ordered.append(text)
    else:
        ordered = [text for _, text in new_entries]

    # Write the gallery.
    sections = "\n".join(ordered)
    if sections and not sections.startswith("\n"):
        sections = "\n" + sections
    content = HEADER + "\n## Screens\n" + sections + "\n"

    # Ensure a blank line between sections for markdown readability.
    content = re.sub(r"\n{3,}", "\n\n", content)

    os.makedirs(os.path.dirname(gallery_path), exist_ok=True)
    with open(gallery_path, "w") as f:
        f.write(content)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <img_dir> <gallery_path>", file=sys.stderr)
        sys.exit(1)
    build_gallery(sys.argv[1], sys.argv[2])
